# Generated by Django 5.0.9 on 2024-11-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("condition", models.IntegerField()),
                ("front_cover", models.ImageField(upload_to="book_images/")),
                ("back_cover", models.ImageField(upload_to="book_images/")),
                ("middle_page", models.ImageField(upload_to="book_images/")),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
            ],
        ),
    ]
