# Generated by Django 5.0.9 on 2024-11-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="back_cover",
        ),
        migrations.RemoveField(
            model_name="book",
            name="front_cover",
        ),
        migrations.RemoveField(
            model_name="book",
            name="middle_page",
        ),
    ]
