# Generated by Django 5.0.9 on 2024-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_back_cover_remove_book_front_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isrented",
            field=models.BooleanField(default=False),
        ),
    ]
